# --------------------------------------------------
# DATABASE — H2 (Replaced RDS MYSQL)
# --------------------------------------------------
spring.datasource.url=jdbc:h2:mem:libappdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --------------------------------------------------
# JPA / HIBERNATE (Updated for H2)
# --------------------------------------------------
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console