INSERT INTO books (cdd, titulo, autor) VALUES 
('020', 'Introdução à Biblioteconomia', 'Maria Souza'),
('510', 'Fundamentos de Álgebra', 'João Pereira'),
('820', 'Contos Modernos', 'Ana Lima'),
('460', 'Redes de Computadores', 'Carlos Mendes'),
('370', 'Educação e Sociedade', 'Fernanda Alves'),
('610', 'Anatomia Humana', 'Ricardo Oliveira'),
('330', 'Economia Global', 'Beatriz Santos'),
('540', 'Química Experimental', 'Paulo Fernandes'),
('910', 'Atlas Geográfico', 'Júlia Martins'),
('621', 'Eletrônica Aplicada', 'Marcelo Costa'),
('150', 'Psicologia Cognitiva', 'Camila Rocha'),
('700', 'História da Arte', 'Rodrigo Moreira'),
('780', 'Teoria Musical', 'Patrícia Nogueira'),
('300', 'Introdução às Ciências Sociais', 'Felipe Azevedo'),
('520', 'Astronomia Básica', 'Larissa Carvalho'),
('860', 'Poesia Brasileira Contemporânea', 'Thiago Barros'),
('010', 'Bibliografia', 'Carlos Silva'),
('020', 'Ciência da Informação', 'Ana Costa'),
('030', 'Enciclopédias Gerais', 'Roberto Almeida'),
('040', 'Não atribuído', 'Sistema Decimal'),
('050', 'Publicações Seriadas Gerais', 'Editora Abril'),
('060', 'Organizações Gerais e Museologia', 'Museu Nacional'),
('070', 'Jornalismo', 'José Rodrigues'),
('080', 'Coletâneas Gerais', 'Vários Autores'),
('090', 'Manuscritos e Livros Raros', 'Acervo Histórico');